### ISSUE TITLE
Kodi 20 ?

### ISSUE THREAD

**Issue by Cygn** [idorel77/CarPc-Carbon-K19#2]
Hello,
Long time user here. Thx for your hard work, it certainly makes my kodi experience great !
I'm using it on a RPI4/LE with a 7" touch screen as an audio jukebox, and I couldn't come up with a better experience than this skin. 
I was holding to K18 to avoid the hassle to reconfigure everything back to my liking. But, alas, I need to take the update route because of extensions... 
So, is it possible to make the skin work on Kodi 20 ? 
Best, S

**Comment by idorel77** [comment]
Hi, did you changed gui version in addon.xml?

**Comment by Cygn** [comment]
Thx, setting it to 5.16.0 made the trick. Will let you know if any issues arise.
